# Generated by Django 5.2.8 on 2025-11-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityrule',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='scheduling.eventtype'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
