# Generated by Django 5.2.8 on 2025-11-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_availabilityrule_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='duration',
            field=models.IntegerField(default=3),
        ),
    ]
