# Generated by Django 5.2.8 on 2025-11-21 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_eventtype_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(24.0)]),
        ),
    ]
