# Generated by Django 5.2.8 on 2025-11-21 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_eventtype_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
