# Generated by Django 5.2.8 on 2025-11-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_eventtype_bufferafter_eventtype_bufferbefore'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityrule',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
