# Generated by Django 5.2.8 on 2025-11-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_availabilityrule_isavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
