# Generated by Django 5.2.8 on 2025-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_eventtype_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='eventtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
