# Generated by Django 5.2.8 on 2025-11-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_alter_eventtype_options_eventtype_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
