# Generated by Django 5.2.8 on 2025-11-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_booking_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityrule',
            name='day',
        ),
    ]
