# Generated by Django 5.2.8 on 2025-11-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_remove_availabilityrule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityrule',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
