# Generated by Django 5.2.8 on 2025-11-21 07:10

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatars/default.jpg', upload_to=users.models.avatar_upload_path),
        ),
    ]
